### ISSUE TITLE
SimpleTriggerImpl members not being serialized

### ISSUE THREAD

**Issue by ashitanojoe** [Nanoko/quartznet-mongodb#19]
SimpleTriggerImpl members `RepeatCount`, `RepeatInterval`, and `TimesTriggered` are not being serialized, causing Jobs to only be triggered once and then deleted.

I am fairly new to Quartz, but I do have quite a bit of experience with MongoDB. I found that AutoMap was not mapping these members, and was only mapping the members that were explicitly mapped. Updating the mapping convention registration to the new method (away from the deprecated `BsonClassMap.RegisterConventions`) resolved the issue. Here are my changes:
https://github.com/ashitanojoe/quartznet-mongodb/commit/d78894f82ae7abad647167080ccf9463b3c70c6d

While this resolved my issues, I am not familiar enough with Quartz to know if this is the correct solution. If you would like a Pull Request let me know.

**Comment by Nanoko** [comment]
I am not sure the merged issue #21 resolved your case. Could you please send a pull request with your changes ?

**Comment by ashitanojoe** [comment]
Pull request sent. #23
