### ISSUE TITLE
Does this support instances running in different processes or machines?

### ISSUE THREAD

**Issue by lsanil** [Nanoko/quartznet-mongodb#2]
This is not a bug, but more like understanding use case scenarios. But I did not find a way to ask this question.

Thanks for sharing the code! I downloaded the code and started playing with it. Works great on a single instance. Code uses lock on many JobStore methods.  

I am not sure if the JobStore works if I start instances on different machines or start multiple instances on the same machine since job store uses lock? By multiple instances, I meant instance having same name, but different instance id and all of them pointing to same database.

Please clarify.

**Comment by Nanoko** [comment]
That's the way I use it in my production environment : instances having same name but different id (absolutely vital!) running on different machines connected to the same mongodb replica set. It looks working to me with decades or hundreds triggers with a mix of regular scheduled ones and fire-once ones.
I validated failure scenarios for scheduled triggers on a workstation with 8 instances and randomly killing them. The fire-once triggers may not resume in every case.

In the latest version (unlike first one where locking were aggressive), the locks are only part of the trigger acquisition process then act as a watchdog to free triggers acquired by uncleanly stopped instances.

**Comment by lsanil** [comment]
Thank you Nonoko for clarification!
