### ISSUE TITLE
Unable to deserialize JobDataMap

### ISSUE THREAD

**Issue by isaacabraham** [Nanoko/quartznet-mongodb#22]
I'm storing data in the JobDataMap as a POCO e.g.

var data = new Person { Name = "Isaac", Age = 33 };
jobDetail.JobDataMap.Add("data", data);

This gets serialized something like this: -

"JobDataMap" : {
    "data" : {
      "_t" : "Person",
      "Name" : "Isaac"
      "Age" : 33
    }
}

When the trigger for the job fires, I get the following error: -

An exception of type 'MongoDB.Bson.BsonSerializationException' occurred in MongoDB.Bson.dll but was not handled in user code
Additional information: Unknown discriminator value 'Person'.

The error occurs in JobDataMapSerializer.cs.

Is this something I'm doing wrong or is this sort of functionality unsupported?

Thanks

**Comment by Nanoko** [comment]
Unrelated to this context, you may need to register your POCO with MongoDB

``` csharp
BsonSerializer.LookupSerializer(typeof(Person));
```

**Comment by isaacabraham** [comment]
Result :-) Worked perfectly - thanks. Why do I need to do this though - does that LookupSerializer also let MongoDB know about that type for deserialization?
