### ISSUE TITLE
MongoDB Driver 1.5 issue

### ISSUE THREAD

**Issue by Needleski** [Nanoko/quartznet-mongodb#3]
There is an issue when using the new MongoDB V1.5 driver.

Query.All() now expects a name and an IEnumerable of BsonValue.

Modifying JobStore.cs line 1248 from:

Query.All("_id", resumedGroup);

To:

Query.All("_id", new List<BsonValue>() {resumedGroup}));

Fixed the issue.

**Comment by Nanoko** [comment]
Would you mind validate for your use case this fix instead : replace the whole foreach loop at 1245 with the following one-liner.

this.PausedTriggerGroups.Remove(
                        Query.All("_id", new BsonArray(resumedGroups)));

I will push this update in the NuGet package if OK.

**Comment by Needleski** [comment]
Hi,

Yes, that works perfectly for me too!!

**Comment by Nanoko** [comment]
Just commited this here and on nuget.org.
Thanks for your report !
