### ISSUE TITLE
Does clustering work as expected?

### ISSUE THREAD

**Issue by tlnagy** [Nanoko/quartznet-mongodb#4]
Does clustering work with this MongoDB implementation?

**Comment by Nanoko** [comment]
Please refer to issue #2 or be more specific if you are experiencing any problem

**Comment by tlnagy** [comment]
I was referring to [clustering](http://quartznet.sourceforge.net/tutorial/lesson_11.html) as per the Quartz documentation. I tried setting up Quartz to use this package and to set isClustered to true and received errors that suggested that isClustered is missing. Clustering only works with AdoJobStore according to the [official docs](http://quartz-scheduler.org/documentation/quartz-2.x/configuration/ConfigJDBCJobStoreClustering) and I was wondering whether this project supported that. Thank you.

**Comment by Nanoko** [comment]
You don't have to worry about the clustered and persistent parameters, they are managed by the job store (responds "true") as properties of the IJobStore interface.
